version: "2"

services:

  fcrepo:
    image: fcrepoapix/apix-fcrepo:4.7.1-1
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"

  fuseki:
    image: fcrepoapix/apix-fuseki:2.4.1-1
    env_file: .env
    container_name: fuseki
    ports:
      - "${FUSEKI_PORT}:${FUSEKI_PORT}"
    
  solr:
    image: fcrepoapix/fcrepo-solr:4.10.3
    build: solr/4.10.3
    container_name: solr
    env_file: .env
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"

  toolbox:
    image: fcrepoapix/fcrepo-toolbox:4.7.2
    build: toolbox/4.7.2
    container_name: toolbox
    env_file: .env
    ports:
      - "${REINDEXING_PORT}:${REINDEXING_PORT}"
      - "${DEMO_WWW_PORT}:${DEMO_WWW_PORT}"
      - "${LDPATH_PORT}:${LDPATH_PORT}"
    links:
      - fcrepo:localhost
    depends_on:
      - fcrepo
      - fuseki
      - solr
